services:
  nexo-bot:
    image: ksmaiotupnvj/nexo-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexo_bot
    restart: always
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./prompts:/app/prompts
      - ./data:/app/data

    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - hydroponic_network

networks:
  hydroponic_network:
    external: true
