services:
  nexo-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexo_bot
    restart: always
    env_file:
      - .env

    volumes:
      - ./prompts:/app/prompts

    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - hydroponic_network

networks:
  hydroponic_network:
    external: true
