"""add_gcal_event_id_to_scheduled_events

Revision ID: 2faacb1e41c6
Revises: e73682910301
Create Date: 2026-09-02 17:34:47.453113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2faacb1e41c6"
down_revision: Union[str, Sequence[str], None] = "e73682910301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scheduled_events",
        sa.Column("gcal_event_id", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_scheduled_events_gcal_event_id"),
        "scheduled_events",
        ["gcal_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduled_events_gcal_event_id"), table_name="scheduled_events"
    )
    op.drop_column("scheduled_events", "gcal_event_id")
    # ### end Alembic commands ###
