"""create_scheduled_events_table

Revision ID: 32629ef3fa73
Revises: 89c1e963f8d8
Create Date: 2026-08-31 23:11:54.844410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32629ef3fa73"
down_revision: Union[str, Sequence[str], None] = "89c1e963f8d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("broadcast_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("broadcast_message_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_url", sa.String(length=255), nullable=False),
        sa.Column("reminder_intervals", sa.JSON(), nullable=False),
        sa.Column("reminders_sent", sa.JSON(), nullable=False),
        sa.Column("template_name", sa.String(length=100), nullable=False),
        sa.Column("target_role_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_events_id"), "scheduled_events", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_events_id"), table_name="scheduled_events")
    op.drop_table("scheduled_events")
    # ### end Alembic commands ###
