"""create_competitions_table

Revision ID: 4af8bb7f117f
Revises: 6c8f391b4a92
Create Date: 2026-09-06 00:08:39.096914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4af8bb7f117f"
down_revision: Union[str, Sequence[str], None] = "6c8f391b4a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_url", sa.String(length=512), nullable=True),
        sa.Column("guidebook_url", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("target_role_id", sa.BigInteger(), nullable=True),
        sa.Column("reminders_sent", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competitions_deadline"), "competitions", ["deadline"], unique=False
    )
    op.create_index(
        op.f("ix_competitions_guild_id"), "competitions", ["guild_id"], unique=False
    )
    op.create_index(
        op.f("ix_competitions_is_active"), "competitions", ["is_active"], unique=False
    )
    op.create_table(
        "scheduled_announcements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_embed", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_announcements_guild_id"),
        "scheduled_announcements",
        ["guild_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_announcements_scheduled_at"),
        "scheduled_announcements",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_announcements_status"),
        "scheduled_announcements",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduled_announcements_status"), table_name="scheduled_announcements"
    )
    op.drop_index(
        op.f("ix_scheduled_announcements_scheduled_at"),
        table_name="scheduled_announcements",
    )
    op.drop_index(
        op.f("ix_scheduled_announcements_guild_id"),
        table_name="scheduled_announcements",
    )
    op.drop_table("scheduled_announcements")
    op.drop_index(op.f("ix_competitions_is_active"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_guild_id"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_deadline"), table_name="competitions")
    op.drop_table("competitions")
    # ### end Alembic commands ###
