import asyncio
import os
import json
import logging
from datetime import datetime
import aiohttp
import discord
from mcp import ClientSession
from mcp.client.sse import sse_client
from openai import AsyncOpenAI
from db.repository import (
    get_or_create_conversation,
    get_conversation_context,
    save_message,
    log_token_usage,
    count_token,
    MessageRole,
)
import time

logger = logging.getLogger("mcp_client")

# ---------------------------------------------------------
# CONFIGURATION & CONSTANTS
# ---------------------------------------------------------
LLAMA_SERVER_URL = os.environ.get(
    "LLAMA_SERVER_URL", "http://localhost:8080/v1/chat/completions"
)
LLAMA_BASE_URL = LLAMA_SERVER_URL.replace("/chat/completions", "")
LLAMA_API_KEY = os.environ.get("LLAMA_API_KEY", "").strip("\"' \r\n")
MCP_SERVER_URL = os.environ.get("MCP_SERVER_URL", "http://127.0.0.1:8000")

# Load System Prompt
try:
    with open("prompts/system_prompt.md", "r", encoding="utf-8") as f:
        SYSTEM_PROMPT = f.read().strip()
except FileNotFoundError:
    SYSTEM_PROMPT = "You are Nexo, a helpful assistant."
ai_client = AsyncOpenAI(base_url=LLAMA_BASE_URL, api_key=LLAMA_API_KEY or "sk-no-key")


def sanitize_parameters(schema: dict) -> dict:
    """
    Recursively sanitizes JSON schema parameters:
    - Strips '$defs' and all 'title' attributes generated by Pydantic.
    - Simplifies nullable 'anyOf': [{'type': 'T'}, {'type': 'null'}] -> {'type': 'T'}.
    - Trims parameter descriptions to single-line concise text.
    - Removes empty/redundant metadata.
    """
    if not isinstance(schema, dict):
        return schema

    cleaned = {}
    for key, value in schema.items():
        if key in ("title", "$defs"):
            continue

        if key in ("anyOf", "oneOf") and isinstance(value, list):
            non_null = [
                item
                for item in value
                if isinstance(item, dict) and item.get("type") != "null"
            ]
            if len(non_null) == 1:
                sub_cleaned = sanitize_parameters(non_null[0])
                cleaned.update(sub_cleaned)
                continue

        if key == "description" and isinstance(value, str):
            first_line = value.strip().split("\n")[0].split("Args:")[0].strip()
            cleaned[key] = first_line
            continue

        if key == "default" and value is None:
            continue

        if key == "additionalProperties" and value is True:
            continue

        if isinstance(value, dict):
            cleaned[key] = sanitize_parameters(value)
        elif isinstance(value, list):
            cleaned[key] = [
                sanitize_parameters(item) if isinstance(item, dict) else item
                for item in value
            ]
        else:
            cleaned[key] = value

    if cleaned.get("type") == "object" and "properties" not in cleaned:
        cleaned["properties"] = {}

    return cleaned


def sanitize_tool_schema(tool: dict) -> dict:
    """Sanitizes an OpenAI-compatible tool definition to reduce token overhead."""
    if not isinstance(tool, dict):
        return tool

    fn = tool.get("function", {})
    if not fn:
        return tool

    desc = fn.get("description", "")
    if isinstance(desc, str):
        desc = desc.strip().split("\n")[0].split("Args:")[0].strip()

    params = fn.get("parameters", {})
    sanitized_params = sanitize_parameters(params) if isinstance(params, dict) else {}

    return {
        "type": "function",
        "function": {
            "name": fn.get("name", "unknown"),
            "description": desc,
            "parameters": sanitized_params,
        },
    }


def sanitize_tools_list(tools: list) -> list:
    """Applies schema sanitization to a list of tool definitions."""
    if not tools:
        return []
    return [sanitize_tool_schema(t) for t in tools]


async def get_tools_from_mcp_server() -> list:
    # Try a couple of likely endpoints so this client is resilient to
    # whether the streamable MCP app is mounted at `/` or `/mcp`.
    candidates = [MCP_SERVER_URL.rstrip("/") + "/sse"]

    def _get_field(obj, key):
        if obj is None:
            return None
        if isinstance(obj, dict):
            return obj.get(key)
        return getattr(obj, key, None)

    last_exc = None
    for url in candidates:
        try:
            async with sse_client(url) as (read_stream, write_stream):
                async with ClientSession(read_stream, write_stream) as session:
                    await session.initialize()
                    tools_response = await session.list_tools()

                    llm_tools = []
                    for tool in getattr(tools_response, "tools", []) or []:
                        name = _get_field(tool, "name")
                        desc = _get_field(tool, "description") or ""

                        # input schema may be provided under different names or as a string
                        raw_schema = (
                            _get_field(tool, "inputSchema")
                            or _get_field(tool, "input_schema")
                            or _get_field(tool, "parameters")
                            or _get_field(tool, "schema")
                        )

                        parameters = None
                        if raw_schema:
                            if isinstance(raw_schema, str):
                                try:
                                    parameters = json.loads(raw_schema)
                                except Exception:
                                    parameters = None
                            elif isinstance(raw_schema, dict):
                                parameters = raw_schema

                        if not parameters:
                            parameters = {
                                "type": "object",
                                "properties": {},
                                "additionalProperties": True,
                            }

                        if name:
                            llm_tools.append(
                                {
                                    "type": "function",
                                    "function": {
                                        "name": name,
                                        "description": desc,
                                        "parameters": parameters,
                                    },
                                }
                            )

                    return llm_tools
        except Exception as e:
            last_exc = e
            continue

    # If we couldn't connect to any candidate URL, raise a clear error.
    raise RuntimeError(f"Unable to fetch tools from MCP server: {last_exc}")


async def execute_mcp_tool(tool_name: str, arguments: dict) -> str:
    """
    Execute an MCP tool by calling the actual MCP server.
    """
    candidates = [MCP_SERVER_URL.rstrip("/") + "/sse"]
    for url in candidates:
        try:
            async with sse_client(url) as (read_stream, write_stream):
                async with ClientSession(read_stream, write_stream) as session:
                    await session.initialize()
                    result = await session.call_tool(tool_name, arguments)

                    if hasattr(result, "content") and isinstance(result.content, list):
                        text_results = []
                        for content in result.content:
                            if content.type == "text":
                                text_results.append(content.text)

                        combined = "\n".join(text_results)
                        return combined
                    else:
                        return str(result)
        except Exception as e:
            error_msg = f"Error calling MCP tool '{tool_name}' at {url}: {str(e)}"
            logger.error(error_msg)
            continue

    return "⚠️ Tool execution failed or unable to connect."


async def check_services_health():
    """Returns True if both services are up, False and an error message otherwise."""
    try:
        async with aiohttp.ClientSession() as session:
            # Check llama-server
            try:
                llama_headers = {}
                key = os.environ.get("LLAMA_API_KEY", LLAMA_API_KEY).strip("\"' \r\n")
                if key and key != "sk-no-key":
                    llama_headers["Authorization"] = f"Bearer {key}"

                async with session.get(
                    f"{LLAMA_BASE_URL.replace('/v1', '')}/health",
                    headers=llama_headers,
                    timeout=aiohttp.ClientTimeout(total=2),
                ) as response:
                    if response.status != 200:
                        return (
                            False,
                            "⚠️ **llama-server** responded with an error (non-200).",
                        )
            except Exception:
                return (
                    False,
                    "❌ **llama-server** is OFFLINE. Please start the LLM server.",
                )

            # Check MCP server
            try:
                mcp_ok = False
                # 1. Try /sse endpoint
                try:
                    async with session.get(
                        f"{MCP_SERVER_URL.rstrip('/')}/sse",
                        timeout=aiohttp.ClientTimeout(total=2),
                    ) as response:
                        if response.status in (200, 400, 405):
                            mcp_ok = True
                except Exception:
                    pass

                # 2. Try root endpoint if /sse was not reached
                if not mcp_ok:
                    async with session.get(
                        f"{MCP_SERVER_URL}/", timeout=aiohttp.ClientTimeout(total=2)
                    ) as response:
                        if response.status in (200, 400, 405):
                            mcp_ok = True

                if not mcp_ok:
                    return (
                        False,
                        "⚠️ **MCP Server** responded with an error.",
                    )
            except Exception:
                return (
                    False,
                    "❌ **MCP Server** is OFFLINE. Please start the MCP server.",
                )

    except Exception as e:
        return False, f"An error occurred while checking servers: {str(e)}"

    return True, "All systems go"


async def process_with_mcp_tools(
    bot,
    user_id: int,
    user_name: str,
    user_question: str,
    max_iterations: int = 4,
    ctx_obj=None,
):
    """
    Process a user question with MCP tool support, latency tracking, token usage analytics, and context memory.
    Returns (reply_text, used_tools_boolean, usage_dict, elapsed_s)
    """
    start_time = time.perf_counter()

    channel_id = (
        getattr(ctx_obj.channel, "id", None)
        if ctx_obj and hasattr(ctx_obj, "channel")
        else None
    )
    conv = await get_or_create_conversation(user_id, channel_id)

    summary, recent_messages, history_tokens = await get_conversation_context(user_id)

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
    ]

    if summary:
        messages.append(
            {
                "role": "system",
                "content": f"<past_conversation_summary>\n{summary}\n</past_conversation_summary>",
            }
        )

    messages.extend(recent_messages)

    current_time_str = datetime.now().strftime("%A, %d %B %Y - %H:%M WIB")

    # Extract Channel & Voice Channel info from ctx_obj
    channel_name = "Unknown"
    is_voice_chat = False
    user_vc_name = "None"

    if ctx_obj and hasattr(ctx_obj, "channel") and ctx_obj.channel:
        channel_name = getattr(ctx_obj.channel, "name", "Unknown")
        is_voice_chat = isinstance(
            ctx_obj.channel, (discord.VoiceChannel, discord.StageChannel)
        )

    user_obj = getattr(ctx_obj, "author", getattr(ctx_obj, "user", None))
    if (
        user_obj
        and hasattr(user_obj, "voice")
        and user_obj.voice
        and user_obj.voice.channel
    ):
        user_vc_name = user_obj.voice.channel.name

    dynamic_user_prompt = (
        f"<system_context>\n"
        f"Current Time WIB: {current_time_str}\n"
        f"User: {user_name} (<@{user_id}>)\n"
        f"Current Channel: #{channel_name} (Is Voice Chat: {is_voice_chat})\n"
        f"User Connected Voice Channel: {user_vc_name}\n"
        f"</system_context>\n"
        f"{user_question}"
    )

    messages.append({"role": "user", "content": dynamic_user_prompt})

    used_tools = False
    total_prompt_tokens = 0
    total_completion_tokens = 0

    guild_id = None
    if ctx_obj:
        if hasattr(ctx_obj, "guild") and ctx_obj.guild:
            guild_id = ctx_obj.guild.id

    for iteration in range(max_iterations):
        all_tools = []
        if getattr(bot, "ai_tools", None):
            all_tools.extend(bot.ai_tools)
        if getattr(bot, "cached_mcp_tools", None):
            all_tools.extend(bot.cached_mcp_tools)

        kwargs = {
            "model": "local-model",
            "messages": messages,
            "temperature": 0.7,
            "top_p": 0.95,
            "max_tokens": 1024,
        }
        # On the last iteration, omit tools to force the model to summarize existing data into text
        if all_tools and iteration < (max_iterations - 1):
            kwargs["tools"] = sanitize_tools_list(all_tools)

        try:
            response = await ai_client.chat.completions.create(**kwargs)

            # Accumulate token usage from response if available
            if hasattr(response, "usage") and response.usage:
                total_prompt_tokens += response.usage.prompt_tokens or 0
                total_completion_tokens += response.usage.completion_tokens or 0

            choice = response.choices[0]
            message = choice.message

            # Check if the model wants to call a tool
            if message.tool_calls and iteration < (max_iterations - 1):
                used_tools = True
                messages.append(message)

                for tool_call in message.tool_calls:
                    tool_name = tool_call.function.name
                    args = tool_call.function.arguments
                    arguments = {}

                    if isinstance(args, str):
                        try:
                            arguments = json.loads(args) if args.strip() else {}
                        except (json.JSONDecodeError, TypeError) as json_err:
                            logger.warning(
                                f"Malformed JSON arguments from model for tool '{tool_name}': {args} | Error: {json_err}"
                            )
                            messages.append(
                                {
                                    "role": "tool",
                                    "tool_call_id": tool_call.id,
                                    "name": tool_name,
                                    "content": f"Error: Format argumen JSON tidak valid ({json_err}). Harap gunakan JSON yang valid.",
                                }
                            )
                            continue
                    elif isinstance(args, dict):
                        arguments = args

                    logger.info(f"Executing tool: {tool_name} with args: {arguments}")

                    try:
                        if (
                            hasattr(bot, "local_tool_handlers")
                            and tool_name in bot.local_tool_handlers
                        ):
                            import inspect

                            handler = bot.local_tool_handlers[tool_name]
                            sig = inspect.signature(handler)
                            if "ctx_obj" in sig.parameters:
                                result = await handler(arguments, ctx_obj=ctx_obj)
                            else:
                                result = await handler(arguments)
                        else:
                            result = await execute_mcp_tool(tool_name, arguments)
                    except Exception as tool_exec_err:
                        logger.error(
                            f"Unhandled exception executing tool '{tool_name}': {tool_exec_err}",
                            exc_info=True,
                        )
                        result = f"Gagal mengeksekusi fungsi '{tool_name}' karena kendala internal. Harap beri tahu pengguna untuk mencoba sesaat lagi."

                    # Ensure result is always a string for OpenAI API message content
                    if not isinstance(result, str):
                        result = (
                            json.dumps(result, ensure_ascii=False)
                            if isinstance(result, (dict, list))
                            else str(result)
                        )

                    messages.append(
                        {
                            "role": "tool",
                            "tool_call_id": tool_call.id,
                            "name": tool_name,
                            "content": result,
                        }
                    )
                    try:
                        parsed = json.loads(result)
                        if isinstance(parsed, list):
                            log_msg = f"[Retrieved {len(parsed)} data items]"
                        elif isinstance(parsed, dict):
                            log_msg = f"[Retrieved JSON object with {len(parsed.keys())} keys]"
                        else:
                            log_msg = str(result)[:100] + (
                                "..." if len(str(result)) > 100 else ""
                            )
                    except json.JSONDecodeError, TypeError:
                        log_msg = str(result)[:100] + (
                            "..." if len(str(result)) > 100 else ""
                        )

                    logger.info(f"Tool '{tool_name}' result: {log_msg}")

                continue
            else:
                reply = (
                    message.content
                    or "Maaf, Nexo belum memiliki respon untuk hal tersebut."
                )

                # Fallback estimation if usage was not returned
                if total_prompt_tokens == 0:
                    total_prompt_tokens = sum(
                        [
                            await count_token(str(m.get("content", "")))
                            if isinstance(m, dict)
                            else await count_token(str(getattr(m, "content", "")))
                            for m in messages
                        ]
                    )
                if total_completion_tokens == 0:
                    total_completion_tokens = await count_token(reply)

                total_tokens = total_prompt_tokens + total_completion_tokens
                elapsed_s = time.perf_counter() - start_time
                latency_ms = int(elapsed_s * 1000)

                # Persist message history with exact token count
                user_msg_tokens = await count_token(user_question)
                reply_msg_tokens = await count_token(reply)
                await save_message(
                    conv.id,
                    MessageRole.USER,
                    user_question,
                    token_count=user_msg_tokens,
                )
                await save_message(
                    conv.id,
                    MessageRole.ASSISTANT,
                    reply,
                    token_count=reply_msg_tokens,
                )

                # Log token usage asynchronously in DB
                asyncio.create_task(
                    log_token_usage(
                        guild_id=guild_id,
                        user_id=user_id,
                        username=user_name,
                        prompt_tokens=total_prompt_tokens,
                        completion_tokens=total_completion_tokens,
                        total_tokens=total_tokens,
                        latency_ms=latency_ms,
                    )
                )

                usage_data = {
                    "prompt_tokens": total_prompt_tokens,
                    "completion_tokens": total_completion_tokens,
                    "total_tokens": total_tokens,
                    "latency_ms": latency_ms,
                }
                return reply, used_tools, usage_data, elapsed_s

        except Exception as e:
            logger.error(
                f"Unexpected error in process_with_mcp_tools: {e}",
                exc_info=True,
            )
            elapsed_s = time.perf_counter() - start_time
            return (
                "Maaf, Nexo mengalami kendala teknis saat memproses permintaanmu. Silakan coba sesaat lagi ya! 🤖",
                False,
                {},
                elapsed_s,
            )

    elapsed_s = time.perf_counter() - start_time
    return (
        "I've tried using tools but couldn't complete your request. Please try again or rephrase your question.",
        used_tools,
        {},
        elapsed_s,
    )
