import os
import discord
import time
import asyncio
import logging
from discord.ext import commands
from discord import app_commands
from utils.mcp_client import (
    process_with_mcp_tools,
    check_services_health,
    get_tools_from_mcp_server,
)

logger = logging.getLogger("agent_orchestrator")


class AgentOrchestrator(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.worker_task = None

    async def cog_load(self):
        # Ensure queue and lock exist on bot
        if not hasattr(self.bot, "message_queue"):
            self.bot.message_queue = asyncio.Queue()
        if not hasattr(self.bot, "bot_lock"):
            self.bot.bot_lock = asyncio.Lock()
        # Load tools on startup
        try:
            if not hasattr(self.bot, "cached_mcp_tools"):
                self.bot.cached_mcp_tools = await get_tools_from_mcp_server()
        except Exception as e:
            logger.warning(f"MCP Server not available on startup: {e}")

        # Start worker
        self.worker_task = asyncio.create_task(self.worker())
        logger.info("Agent Orchestrator Worker started.")

    async def cog_unload(self):
        if self.worker_task:
            self.worker_task.cancel()

    async def worker(self):
        """Constantly watches the queue and processes requests one by one"""
        while True:
            # Wait until a request is available
            try:
                queue_item = await self.bot.message_queue.get()
            except asyncio.CancelledError:
                break

            # Unpack the queue item
            if len(queue_item) == 3:
                ctx_obj, prompt, queued_time = queue_item
            else:
                ctx_obj, prompt = queue_item
                queued_time = time.time()

            is_interaction = isinstance(ctx_obj, discord.Interaction)
            user_id = ctx_obj.user.id if is_interaction else ctx_obj.author.id
            user_name = ctx_obj.user.name if is_interaction else ctx_obj.author.name

            async with self.bot.bot_lock:
                is_expired = (time.time() - queued_time) > 850
                wait_msg = None

                if not is_expired:
                    try:
                        if is_interaction:
                            await ctx_obj.edit_original_response(
                                content="*Nexo is thinking... 💭*"
                            )
                        else:
                            wait_msg = await ctx_obj.reply("*Nexo is thinking... 💭*")
                    except discord.NotFound:
                        is_expired = True

                try:
                    reply, used_tools = await process_with_mcp_tools(
                        self.bot, user_id, user_name, prompt, ctx_obj=ctx_obj
                    )

                    if reply:
                        if used_tools:
                            safe_reply = reply[:4096]
                            embed = discord.Embed(
                                title="✨ Nexo Response",
                                description=safe_reply,
                                color=discord.Color.blue(),
                            )
                            embed.set_footer(text="Generated by Nexo KSM AIoT")
                            if is_expired:
                                await ctx_obj.channel.send(
                                    content=f"<@{user_id}> Sorry for the long wait! Here is your response:",
                                    embed=embed,
                                )
                            else:
                                if is_interaction:
                                    await ctx_obj.edit_original_response(
                                        content=None, embed=embed
                                    )
                                else:
                                    await wait_msg.edit(content=None, embed=embed)
                        else:
                            if is_expired:
                                if len(reply) > 2000:
                                    chunks = [
                                        reply[i : i + 2000]
                                        for i in range(0, len(reply), 2000)
                                    ]
                                    await ctx_obj.channel.send(
                                        f"<@{user_id}> {chunks[0]}"
                                    )
                                    for chunk in chunks[1:]:
                                        await ctx_obj.channel.send(chunk)
                                else:
                                    await ctx_obj.channel.send(f"<@{user_id}> {reply}")
                            else:
                                if len(reply) > 2000:
                                    chunks = [
                                        reply[i : i + 2000]
                                        for i in range(0, len(reply), 2000)
                                    ]
                                    if is_interaction:
                                        await ctx_obj.edit_original_response(
                                            content=chunks[0]
                                        )
                                    else:
                                        await wait_msg.edit(content=chunks[0])
                                    for chunk in chunks[1:]:
                                        await ctx_obj.channel.send(chunk)
                                else:
                                    if is_interaction:
                                        await ctx_obj.edit_original_response(
                                            content=reply
                                        )
                                    else:
                                        await wait_msg.edit(content=reply)
                        logger.info(f"Sent response (length: {len(reply)} chars)")
                except discord.NotFound:
                    # The wait message (wait_msg) might have been deleted by the bot's own action (e.g., clear_messages tool)
                    # So we just send the reply as a new message without the connection error message.
                    await ctx_obj.channel.send(f"<@{user_id}> {reply}")
                except Exception as e:
                    if is_expired:
                        await ctx_obj.channel.send(
                            f"<@{user_id}> Oops, sorry, there was an error while I was thinking: {str(e)} 😭"
                        )
                    else:
                        if is_interaction:
                            await ctx_obj.edit_original_response(
                                content=f"Oops, sorry, there was an error while I was thinking: {str(e)} 😭"
                            )
                        else:
                            if wait_msg:
                                await wait_msg.edit(
                                    content=f"Oops, sorry, there was an error while I was thinking: {str(e)} 😭"
                                )
                finally:
                    self.bot.message_queue.task_done()

    @app_commands.command(name="tanya", description="Ask Nexo about KSM AIoT projects!")
    @app_commands.describe(pertanyaan="What do you want to ask?")
    async def tanya(self, interaction: discord.Interaction, pertanyaan: str):
        await interaction.response.defer(ephemeral=False)

        is_healthy, error_msg = await check_services_health()
        if not is_healthy:
            await interaction.edit_original_response(content=error_msg)
            return

        if not getattr(self.bot, "cached_mcp_tools", []):
            try:
                self.bot.cached_mcp_tools = await get_tools_from_mcp_server()
            except Exception:
                await interaction.edit_original_response(
                    content="⚠️ Failed to fetch tools from the MCP Server."
                )
                return

        logger.info(f"User: {interaction.user.name} asked: {pertanyaan}")

        position = self.bot.message_queue.qsize()
        if self.bot.bot_lock.locked():
            position += 1

        if position > 0:
            await interaction.edit_original_response(
                content=f"⏳ *Your question is currently queued at position #{position}. Please wait a moment!*"
            )

        await self.bot.message_queue.put((interaction, pertanyaan, time.time()))

    @commands.Cog.listener()
    async def on_message(self, message):
        # Prevents the bot from replying to itself
        if message.author == self.bot.user:
            return

        # Cek apakah bot di-tag dalam pesan
        if self.bot.user.mentioned_in(message) and not message.mention_everyone:
            # Check if it's a command prefix (e.g., typo) ignore
            if message.content.startswith("$"):
                return

            is_healthy, error_msg = await check_services_health()
            if not is_healthy:
                await message.reply(content=error_msg)
                return

            # Fetch 10 previous messages history
            history_msgs = []
            total_chars = 0

            # Get context limit from env variable, default 15000
            max_chars = int(os.environ.get("MAX_GROUP_CONTEXT_CHARS", 15000))

            async for msg in message.channel.history(limit=10, before=message):
                content = msg.clean_content
                if content:
                    # Format: "User: Message"
                    formatted_msg = f"{msg.author.name}: {content}"
                    # If exceeding character limit, stop fetching messages (discard oldest)
                    if total_chars + len(formatted_msg) > max_chars:
                        break
                    history_msgs.append(formatted_msg)
                    total_chars += len(formatted_msg)

            history_msgs.reverse()  # Sort from oldest to newest
            context_text = "\n".join(history_msgs)

            # Remove bot's name from user's message for a cleaner prompt
            user_prompt = message.clean_content.replace(
                f"@{self.bot.user.name}", ""
            ).strip()

            if context_text:
                final_prompt = f"[Channel History Context]\n{context_text}\n\n[User's Message]\n{user_prompt}"
            else:
                final_prompt = user_prompt

            logger.info(
                f"Group Chat User: {message.author.name} tagged bot. History size: {total_chars} chars."
            )

            position = self.bot.message_queue.qsize()
            if self.bot.bot_lock.locked():
                position += 1

            if position > 0:
                await message.reply(
                    f"⏳ *Your question is currently queued at position #{position}. Please wait a moment!*"
                )

            await self.bot.message_queue.put((message, final_prompt, time.time()))


async def setup(bot):
    await bot.add_cog(AgentOrchestrator(bot))
