import discord
import logging
from discord.ext import commands
from utils.mcp_client import LLAMA_BASE_URL, MCP_SERVER_URL

logger = logging.getLogger("core_commands")


class CoreCommands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def ping(self, ctx):
        """Responds with the bot's latency."""
        await ctx.send(f"Pong! Latency: {round(self.bot.latency * 1000)}ms")

    @commands.command()
    async def help(self, ctx):
        """Displays the Nexo bot usage guide."""
        embed = discord.Embed(
            title="🌟 Nexo KSM AIoT Bot Guide",
            description="Hello! I am an AI assistant ready to help you on this server. Here is a list of commands you can use:",
            color=discord.Color.blue(),
        )

        embed.add_field(
            name="💬 Slash Commands",
            value="`/tanya [question]`\nAsk the AI directly (connected to Llama.cpp & IoT tools).",
            inline=False,
        )
        embed.add_field(
            name="🤖 Automatic Features",
            value="- Greet new members in the *welcome* channel\n- Automatically assign roles upon introduction",
            inline=False,
        )
        embed.add_field(
            name="⚙️ Prefix Commands ($)",
            value=(
                "`$help` : Display this message\n"
                "`$ping` : Check bot latency (delay)\n"
                "`$status` : Check LLM and MCP server status\n"
                "`$tools` : See the list of tools the AI can use"
            ),
            inline=False,
        )

        embed.set_footer(text="KSM AI & IoT • Guiding You to the Future 🚀")
        await ctx.send(embed=embed)

    @commands.command()
    async def tools(self, ctx):
        """List all available tools."""
        embed = discord.Embed(
            title="🔧 Nexo AI Tools List",
            description="Here are all the capabilities (tools) currently accessible by the AI:",
            color=discord.Color.green(),
        )

        # 1. Local Tools (from Cogs)
        local_tools = getattr(self.bot, "ai_tools", [])
        if local_tools:
            local_text = ""
            for tool in local_tools:
                name = tool.get("function", {}).get("name", "Unknown")
                local_text += f"• `{name}`\n"
            embed.add_field(
                name="⚙️ Local Discord Tools", value=local_text, inline=False
            )
        else:
            embed.add_field(
                name="⚙️ Local Discord Tools",
                value="*No local tools loaded.*",
                inline=False,
            )

        # 2. MCP Tools (from External Server)
        cached_mcp_tools = getattr(self.bot, "cached_mcp_tools", [])
        if cached_mcp_tools:
            mcp_text = ""
            for tool in cached_mcp_tools:
                name = tool.get("function", {}).get("name", "Unknown")
                mcp_text += f"• `{name}`\n"
            if len(mcp_text) > 1024:
                mcp_text = mcp_text[:1020] + "..."
            embed.add_field(
                name="🌐 External MCP Tools (IoT)", value=mcp_text, inline=False
            )
        else:
            embed.add_field(
                name="🌐 External MCP Tools (IoT)",
                value="*MCP Server is offline or has no tools.*",
                inline=False,
            )

        embed.set_footer(text="Generated by Nexo KSM AIoT")
        await ctx.send(embed=embed)

    @commands.command()
    async def status(self, ctx):
        """Check the status of services."""
        status_messages = ["🔍 Checking service status..."]

        import aiohttp

        # Check llama-server
        logger.info(f"Server llama.cpp: {LLAMA_BASE_URL.replace('/v1', '')}")
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    f"{LLAMA_BASE_URL.replace('/v1', '')}/health",
                    timeout=aiohttp.ClientTimeout(total=5),
                ) as response:
                    if response.status == 200:
                        status_messages.append("✅ llama-server: ONLINE")
                    else:
                        status_messages.append("⚠️ llama-server: RESPONDING (non-200)")
        except Exception:
            status_messages.append("❌ llama-server: OFFLINE")

        # Check MCP server
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    f"{MCP_SERVER_URL}/", timeout=aiohttp.ClientTimeout(total=5)
                ) as response:
                    if response.status == 200:
                        status_messages.append("✅ MCP Server: ONLINE")
                    else:
                        status_messages.append("⚠️ MCP Server: RESPONDING (non-200)")
        except Exception:
            status_messages.append("❌ MCP Server: OFFLINE")

        await ctx.send("\n".join(status_messages))

    @commands.command()
    @commands.is_owner()
    async def sync(self, ctx):
        """Syncs slash commands to the current guild."""
        await ctx.send("🔄 Syncing commands...")
        self.bot.tree.copy_global_to(guild=ctx.guild)
        await self.bot.tree.sync(guild=ctx.guild)
        await ctx.send("✅ Successfully synced slash commands in this server!")

    @commands.command()
    async def clear(self, ctx, limit: int = 100):
        """Deletes messages in bulk or one by one with a delay."""
        if not ctx.author.guild_permissions.manage_messages:
            return await ctx.send("❌ You do not have Manage Messages permission.")

        await ctx.send(f"🧹 Starting deletion of {limit} messages...")

        try:
            # channel.purge() automatically handles bulk_delete (<14 days) and single delete (>14 days)
            deleted = await ctx.channel.purge(limit=limit + 2)
            await ctx.send(
                f"✅ Successfully deleted {len(deleted)} messages!", delete_after=5
            )
        except discord.Forbidden:
            await ctx.send("❌ Bot does not have Manage Messages permission.")
        except discord.HTTPException as e:
            await ctx.send(f"❌ HTTP Error occurred: {e}")
        except Exception as e:
            await ctx.send(f"❌ An error occurred: {e}")


async def setup(bot):
    await bot.add_cog(CoreCommands(bot))
